Samsung Audio notification fallback to http to handle cooldown period
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #1064
Opened 2023-11-08 06:31 UTC by raj-1219

These changes are being added to handle cooldown period in certain speaker models. After the notification is played, the speaker assumes the notification to keep on playing for sometime. During this period, if another message is played, it sends "ok" response for PausePlaybackEvent and the notification actually fails.

2023-11-08 20:18 UTC, cjswedes requested changes
lua check fails due to extra whitespace:
```
Checking drivers/SmartThings/samsung-audio/src/command.lua 1 warning

    drivers/SmartThings/samsung-audio/src/command.lua:407:6: (W612) line contains trailing whitespace
```

2023-11-09 09:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=1064) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=1064) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=1064) it.</sub>

2023-11-09 15:19 UTC, cjswedes approved these changes

2023-11-13 06:33 UTC, amit3barthwal approved these changes
Cooldown period handled.. LGTM

2023-11-13 15:21 UTC, merged