aeotec heavy duty switch added
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #1109
Opened 2023-12-11 10:47 UTC by ronie-z-wave

2024-01-02 18:44 UTC, greens approved these changes
I appreciate the tests.

2024-01-02 18:45 UTC, greens requested changes
Ah wait, there are significant numbers of new test failures.

2024-01-02 18:48 UTC, greens commented on drivers/SmartThings/zwave-switch/src/aeotec-heavy-duty/init.lua
> +ge_switch:run()
because this is a dub-driver, you need to define a `can_handle` function and should not be registering for defaults

2024-01-09 14:45 UTC, lelandblue commented
Hey @ronie-z-wave Please see the comments made on this PR and include the changes requested at your nearest opportunity to help move this forward, thank you!

2024-01-24 15:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=1109) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=1109) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ronie-z-wave<br/>:x: mh-zwave<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=1109) it.</sub>

2024-01-24 20:01 UTC, greens commented on drivers/SmartThings/zwave-switch/src/aeotec-heavy-duty/init.lua
> +local defaults = require "st.zwave.defaults"
```
    drivers/SmartThings/zwave-switch/src/aeotec-heavy-duty/init.lua:18:7: (W211) unused variable ZwaveDriver
    drivers/SmartThings/zwave-switch/src/aeotec-heavy-duty/init.lua:19:7: (W211) unused variable defaults
```

2024-01-25 07:31 UTC, mh-zwave commented on drivers/SmartThings/zwave-switch/src/aeotec-heavy-duty/init.lua
> +local defaults = require "st.zwave.defaults"
Ah sorry. I will remove them.

2024-01-25 18:41 UTC, greens commented on drivers/SmartThings/zwave-switch/src/aeotec-heavy-duty/init.lua
Either change the copyright date or add back in the credit to the dev.

2024-01-26 19:08 UTC, greens reviewed
Sorry. I should have mentioned this before, but for devices like this, you can just use one fingerprint.

```
  - id: "Aeotec/Heavy Duty"
    deviceLabel: Aeotec Heavy Duty
    manufacturerId: 0x0086
    productId: 0x004E
    deviceProfileName: aeotec-heavy-duty
```

And you can similarly leave out the product type in the preferences and can_handle sections of the code. Empty fields are treated as wildcards for the matching functions.

For example, here's another aeotec switch where we do this: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zwave-switch/fingerprints.yml#L356

2024-01-26 19:09 UTC, greens commented
I would just leave a comment next to the fingerprint indicating it covers the US, EU, and AU versions.

2024-05-09 13:14 UTC, closed without merging

2024-05-09 13:14 UTC, lelandblue commented
Closing this pr because https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1325 was merged. Thank you.