New Devices (Z-Wave Switch): Shelly Switches
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #1192
Opened 2024-01-30 00:17 UTC by lelandblue

This is a PR Request for #Shelly/Qubino devices being added to the Z-Wave Switch Driver. 

There will be a follow on PR for additional devices that will be CxS.

2024-01-30 00:25 UTC, greens approved these changes

2024-01-30 18:47 UTC, greens approved these changes

2024-01-30 21:23 UTC, greens commented on drivers/SmartThings/zwave-switch/fingerprints.yml
> +    deviceProfileName: switch-binary-indicator
the indicator preference here won't work unless you point out which configuration parameter is used here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zwave-switch/src/preferences.lua#L310

2024-01-30 21:25 UTC, greens requested changes
the `switch-binary-indicator` profile needs to change

2024-02-01 16:32 UTC, wkhenon approved these changes

2024-09-19 13:47 UTC, lelandblue commented
Hey @greens can I get a re-review on this PR please, it is ready to merge after that completes. Thank you!

2024-09-19 18:52 UTC, greens approved these changes

2024-09-19 18:53 UTC, greens requested changes
Ah, there are some test failures...

2024-09-19 18:58 UTC, greens commented
working on them

2024-09-19 21:23 UTC, greens approved these changes
I think my changes look great.

2024-09-23 18:13 UTC, merged