[Aqara/Smart Pet Feeder] add new event and fix issues
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #1337
Opened 2024-04-18 05:08 UTC by seojune79

1. add new error status event
2. fix abnormal feeding logs in history tab and life cycle issues

2024-04-18 16:18 UTC, tpmanley approved these changes

2024-04-18 16:53 UTC, greens commented on drivers/Aqara/aqara-feeder/src/init.lua
>    do_payload(device, 4, 24, 85, OP_WRITE, 1, 0)
does this private protocol need to be enabled before the `do_payload` here will actually do anything?

2024-04-19 13:46 UTC, tpmanley requested changes
In my testing when the error state was hit I could no longer open the device card in the app

2024-04-21 22:20 UTC, seojune79 commented
> In my testing when the error state was hit I could no longer open the device card in the app

Can you tell me how you tested it?

2024-04-21 23:30 UTC, tpmanley commented
> > In my testing when the error state was hit I could no longer open the device card in the app
> 
> Can you tell me how you tested it?

I used the button on the feeder to dispense food over and over again until it jammed up

2024-04-21 23:49 UTC, seojune79 commented
> > > In my testing when the error state was hit I could no longer open the device card in the app
> > 
> > 
> > Can you tell me how you tested it?
> 
> I used the button on the feeder to dispense food over and over again until it jammed up

It's hard for me to understand that I cannot open the card because of ["device:mit_event(capabilities.feederOperatingState.feederOperatingState(evt))"](https://github.com/seojune79/SmartThingsEdgeDrivers/blob/9942b52bd4029a52078094144188d00d0baba808/drivers/Aqara/aqara-feeder/src/init.lua#L122).

I don't have the same problem.
- 40sec
- 1min 22sec
[my test](https://drive.google.com/file/d/1Xx-sHUw9sA4QvDfHbPs_prYjO5hZqzAx/view?usp=sharing)

Can you check it again?

2024-04-27 20:43 UTC, tpmanley approved these changes
I tested again and it is now working for me as well

2024-04-29 15:21 UTC, merged