adding maestro thermostat SMT402AD model
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #1499
Opened 2024-07-04 19:37 UTC by gcavalcantistelpro

Replacing the stelpro maestro thermostat model to SMT402AD

2024-07-04 19:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=1499) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=1499) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=1499) it.</sub>

2024-09-19 19:00 UTC, greens requested changes
If the `MaestroStat` model does not (and has never) existed, then the tests in `test_stelpro_thermostat.lua` should be updated to reflect that.

But if it _has_ existed, this should be an _addition_ of a fingerprint, not an amendment.

2024-11-15 19:08 UTC, lelandblue commented
Hey @Brianj94 and @gcavalcantistelpro . Lets go the safe route here. 

Could we leave the existing code in, and just only add new code? For example, lets add a whole fringerprint for the  SMT402AD device and add lines in the subdriver for that device verses removing anything that is existing.  

Please review and adjust, and thank you!

2024-11-18 19:59 UTC, greens commented on drivers/SmartThings/zigbee-thermostat/src/stelpro/init.lua
> +-- Copyright 2024 SmartThings
date

2024-11-18 19:59 UTC, greens commented on drivers/SmartThings/zigbee-thermostat/src/stelpro/stelpro_maestrostat.lua
> +-- Copyright 2024 SmartThings
date

2024-11-18 19:59 UTC, greens commented on drivers/SmartThings/zigbee-thermostat/src/test/test_stelpro_thermostat.lua
> +-- Copyright 2024 SmartThings
date

2024-11-18 21:57 UTC, greens approved these changes

2025-01-09 15:24 UTC, closed without merging