Add Heiman device Chinese name
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #1705
Opened 2024-10-21 07:07 UTC by Detailzc

Add Heiman device Chinese name

2024-11-20 05:49 UTC, Detailzc commented
@lelandblue Hi, please help approve this PR, thank you

2025-01-09 16:07 UTC, lelandblue requested changes
This will be good to go after the removal of the line for the Heiman Motion Sensor

2025-01-09 16:07 UTC, lelandblue commented on tools/localizations/cn.csv
> +"Heiman Motion Sensor",智能人体带光照度探测器
@Detailzc I dont believe we need the line for the "Heiman Motion Sensor" as I see it currently here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/6e4ec75be413951ce8127d6c4dbb71dfd442ce40/tools/localizations/cn.csv#L9

2025-02-28 15:00 UTC, lelandblue approved these changes

2025-02-28 15:00 UTC, merged