[CHAD-8545] Fixes for Zooz Zen 30 sub-driver
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #180
Opened 2022-07-14 13:19 UTC by dsobierajsk

2022-07-14 13:30 UTC, KKlimczukS requested changes
@dsobierajsk 
some unit tests didn't pass:
`Unit test failures in /home/runner/work/SmartThingsEdgeDrivers/SmartThingsEdgeDrivers/drivers/SmartThings/zwave-switch/src/test/test_zooz_zen_30_dimmer_relay.lua:
    Switch capability on command should evoke the correct Z-Wave SETs and GETs with dst_channel 0
    Switch capability off command should evoke the correct Z-Wave SETs and GETs with dst_channel 0`

2022-07-14 13:30 UTC, KKlimczukS commented on drivers/SmartThings/zwave-switch/src/zooz-zen-30-dimmer-relay/init.lua
> +          device:get_field(PROFILE_CHANGED) ~= true then
nit: spacing

2022-07-14 13:50 UTC, KKlimczukS approved these changes

2022-07-18 20:49 UTC, greens approved these changes

2022-07-19 06:58 UTC, merged