[CHAD-8785] Changed heating and cooling range for Aeotec thermostat.
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #192
Opened 2022-07-20 19:10 UTC by Bhavik-T

Changed heating and cooling range for Aeotec thermostat from 0-40°C to 8-28°C.

2022-07-20 19:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=192) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=192) before we can accept your contribution.<br/><hr/>**Bhavik Thati** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=192) it.</sub>

2022-07-27 00:22 UTC, greens approved these changes

2022-08-03 21:29 UTC, bflorian requested changes
OK except for the attribute name issues noted.

2022-08-03 21:29 UTC, bflorian commented on drivers/SmartThings/zwave-thermostat/profiles/base-thermostat-8to20C.yml
> +            key: "temperature.value"
This needs to be `heatingSetpoint.value`. The capability attribute name is `heatingSetpoint`, not `temperature`

2022-08-03 21:29 UTC, bflorian commented on drivers/SmartThings/zwave-thermostat/profiles/base-thermostat-8to20C.yml
> +            key: "temperature.value"
This needs to be `coolingSetpoint.value`. The capability attribute name is `coolingSetpoint `, not `temperature`

2022-10-07 18:27 UTC, iplantemn commented
@greens @bflorian updated capability configuration

2022-10-31 19:17 UTC, lelandblue commented
We need to change "configuration:" to "config:" please take a look @ctowns, per @iplantemn

2022-10-31 19:19 UTC, lelandblue commented
Hello @ctowns "configuration:" to "config:" please?

2022-11-15 23:59 UTC, merged