CHAD-9411: Edited zwave electric meter profile
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #283
Opened 2022-09-29 15:23 UTC by sjl2178

Switched ordering of energy meter and power meter in qubino-3-phase profile to change join icon from energy consumption to power meter. 

https://smartthings.atlassian.net/browse/CHAD-9411?focusedCommentId=1205226&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1205226

2022-09-29 15:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=283) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=283) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=283) it.</sub>

2022-09-29 19:27 UTC, greens requested changes
looks like you accidentally pulled in a different commit

2022-09-30 01:07 UTC, sjl2178 commented
Whoops previous commit, sneaked in there, should be good now.

2022-09-30 18:30 UTC, greens approved these changes

2022-09-30 19:17 UTC, cjswedes approved these changes

2022-09-30 21:22 UTC, merged