[Aqara] Pet Feeder Edge Device Driver
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #596
Opened 2023-03-02 06:43 UTC by seojune79

2023-03-03 00:08 UTC, greens requested changes
We'd like the `Aqara` folder here to be at the same level in the directory structure as the `SmartThings` folder.

2023-03-03 00:14 UTC, greens commented on drivers/SmartThings/aqara/src/init.lua
> +  },
nit: spacing here is off

2023-03-03 00:15 UTC, greens commented on drivers/SmartThings/aqara/src/init.lua
> +      data = data..string.char(tmp)
nit: spacing here

2023-03-03 00:16 UTC, greens commented
It looks like Github Actions ran into some issue running the linter and uploading the driver and didn't maintain the logs of the errors. Hopefully your changes will cause them to run again (successfully).

2023-03-03 00:39 UTC, seojune79 commented on drivers/SmartThings/aqara/src/init.lua
> +  },
OK, I will update the code.

2023-03-03 00:51 UTC, seojune79 commented on drivers/SmartThings/aqara/src/init.lua
> +defaults.register_for_default_handlers(aqara_pet_feeder_handler, aqara_pet_feeder_handler.supported_capabilities)
I referred to the zigbee-button init code.
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zigbee-button/src/init.lua#L107

Could you tell me how to edit it?

2023-03-03 03:37 UTC, seojune79 commented
> We'd like the `Aqara` folder here to be at the same level in the directory structure as the `SmartThings` folder.

OK, I will change the folder according to your guide.

2023-03-03 03:39 UTC, seojune79 commented on drivers/SmartThings/aqara/src/init.lua
> +      data = data..string.char(tmp)
OK, I will edit the code.

2023-03-06 19:03 UTC, greens commented
Just in case you can't see them, here are your luacheck failures:

```
Checking drivers/SmartThings/aqara/src/init.lua   2 warnings

    drivers/SmartThings/aqara/src/init.lua:43:120: (W[6](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4320165114/jobs/7593682112#step:4:7)12) line contains trailing whitespace
    drivers/SmartThings/aqara/src/init.lua:96:13: (W211) unused variable waiting_timer

Checking drivers/SmartThings/aqara/src/test/test_aqara_pet_feeder.lua [7](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4320165114/jobs/7593682112#step:4:8) warnings

    drivers/SmartThings/aqara/src/test/test_aqara_pet_feeder.lua:54:55: (W612) line contains trailing whitespace
    drivers/SmartThings/aqara/src/test/test_aqara_pet_feeder.lua:71:119: (W612) line contains trailing whitespace
    drivers/SmartThings/aqara/src/test/test_aqara_pet_feeder.lua:[8](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4320165114/jobs/7593682112#step:4:9)8:11[9](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4320165114/jobs/7593682112#step:4:10): (W612) line contains trailing whitespace
    drivers/SmartThings/aqara/src/test/test_aqara_pet_feeder.lua:96:[11](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4320165114/jobs/7593682112#step:4:12)9: (W6[12](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4320165114/jobs/7593682112#step:4:13)) line contains trailing whitespace
    drivers/SmartThings/aqara/src/test/test_aqara_pet_feeder.lua:[14](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4320165114/jobs/7593682112#step:4:15)2:11: (W211) unused function reset_status
    drivers/SmartThings/aqara/src/test/test_aqara_pet_feeder.lua:[15](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4320165114/jobs/7593682112#step:4:16)5:119: (W612) line contains trailing whitespace
    drivers/SmartThings/aqara/src/test/test_aqara_pet_feeder.lua:196:119: (W612) line contains trailing whitespace
```

2023-03-06 19:05 UTC, greens commented
please see my note about `git mv` ing these to an Aqara directory on the same level as Smartthings

2023-03-07 14:28 UTC, dljsjr commented
The `Aqara` directory should be a landing place for this and for all future Aqara drivers, so we should probably not have the driver source code files stored at the top level of the manufacturer directory. The new Aqara folder is in the correct place, but the driver code should probably be in a `pet-feeder` subdirectory or something. You can see how the `SmartThings` directory contains several drivers in it as subdirectories, we should do that with Aqara as well.

2023-03-07 14:29 UTC, dljsjr requested changes
The `Aqara` directory should be a landing place for this and for all future Aqara drivers, so we should probably not have the driver source code files stored at the top level of the manufacturer directory. The new Aqara folder is in the correct place, but the driver code should probably be in a `pet-feeder` subdirectory or something. You can see how the `SmartThings` directory contains several drivers in it as subdirectories, we should do that with Aqara as well.

2023-03-07 18:56 UTC, greens commented
```
Checking drivers/Aqara/src/init.lua               2 warnings

    drivers/Aqara/src/init.lua:2:7: (W211) unused variable defaults
    drivers/Aqara/src/init.lua:100:13: (W211) unused variable waiting_timer

Checking drivers/Aqara/src/test/test_aqara_pet_feeder.lua 7 warnings

    drivers/Aqara/src/test/test_aqara_pet_feeder.lua:54:55: (W[6](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4349927260/jobs/7616998315#step:4:7)12) line contains trailing whitespace
    drivers/Aqara/src/test/test_aqara_pet_feeder.lua:[7](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4349927260/jobs/7616998315#step:4:8)1:119: (W612) line contains trailing whitespace
    drivers/Aqara/src/test/test_aqara_pet_feeder.lua:[8](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4349927260/jobs/7616998315#step:4:9)8:11[9](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4349927260/jobs/7616998315#step:4:10): (W612) line contains trailing whitespace
    drivers/Aqara/src/test/test_aqara_pet_feeder.lua:96:[11](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4349927260/jobs/7616998315#step:4:12)9: (W6[12](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4349927260/jobs/7616998315#step:4:13)) line contains trailing whitespace
    drivers/Aqara/src/test/test_aqara_pet_feeder.lua:[14](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4349927260/jobs/7616998315#step:4:15)2:11: (W211) unused function reset_status
    drivers/Aqara/src/test/test_aqara_pet_feeder.lua:[15](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/actions/runs/4349927260/jobs/7616998315#step:4:16)5:119: (W612) line contains trailing whitespace
    drivers/Aqara/src/test/test_aqara_pet_feeder.lua:196:119: (W612) line contains trailing whitespace
```

2023-03-07 22:34 UTC, seojune79 commented
> subdirectories

I have changed the directory structure.

2023-03-09 18:15 UTC, greens approved these changes

2023-03-09 22:39 UTC, dljsjr approved these changes

2023-03-10 16:52 UTC, tpmanley approved these changes
I've been using this driver for a few days and it seems to be working well

2023-04-11 20:33 UTC, merged