Add sengled water leak sensor device
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #615
Opened 2023-03-10 03:35 UTC by anzhuge

1. Modify fingerprints.yml file for sengled water leak sensor.
2. Add the sendled directory under the src directory and add init.lua file under sendled directory.

2023-03-10 03:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=615) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=615) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=615) it.</sub>

2023-04-19 16:09 UTC, lelandblue commented
Hello - @anzhuge the init.lua file in ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\src\sengled is currently uploaded as a submodule. Please update this PR so that the init.lua file is present without a new submodule.

Also, please update the PR name to properly describe this PR, thanks!

you can refer to this other sengled device PR for reference: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/374

2023-04-23 11:30 UTC, anzhuge commented
Hello ***@***.***

As per your request, I have made new modifications and resubmitted the PR at: https://github.com/anzhuge/SmartThingsEdgeDrivers/pull/1




comments:
1. add the init.lua file to the path ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\src\sengled.
2. Modified ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\fingerprints.yml file, a new device type E1L-G7K is added.


Please review and contact us promptly if you have any questions.










At 2023-04-20 00:09:39, "lelandblue" ***@***.***> wrote:

Hello - @anzhuge the init.lua file in ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\src\sengled is currently uploaded as a submodule. Please update this PR so that the init.lua file is present without a new submodule.

Also, please update the PR name to properly describe this PR, thanks!

you can refer to this other sengled device PR for reference: #374

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-04-23 11:50 UTC, anzhuge commented
I'm sorry, please ignore the content.
















At 2023-04-23 19:30:40, "朱葛" ***@***.***> wrote:

Hello ***@***.***

As per your request, I have made new modifications and resubmitted the PR at: https://github.com/anzhuge/SmartThingsEdgeDrivers/pull/1




comments:
1. add the init.lua file to the path ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\src\sengled.
2. Modified ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\fingerprints.yml file, a new device type E1L-G7K is added.


Please review and contact us promptly if you have any questions.










At 2023-04-20 00:09:39, "lelandblue" ***@***.***> wrote:

Hello - @anzhuge the init.lua file in ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\src\sengled is currently uploaded as a submodule. Please update this PR so that the init.lua file is present without a new submodule.

Also, please update the PR name to properly describe this PR, thanks!

you can refer to this other sengled device PR for reference: #374

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-04-23 12:16 UTC, anzhuge commented
Hello ***@***.***

As per your request, I have made new modifications and committed.




comments:
1. add the init.lua file to the path ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\src\sengled.
2. Modified ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\fingerprints.yml file, a new device type E1L-G7K is added.


Please review and contact us promptly if you have any questions.













在 2023-04-23 19:50:19，"朱葛" ***@***.***> 写道：

I'm sorry, please ignore the content.
















At 2023-04-23 19:30:40, "朱葛" ***@***.***> wrote:

Hello ***@***.***

As per your request, I have made new modifications and resubmitted the PR at: https://github.com/anzhuge/SmartThingsEdgeDrivers/pull/1




comments:
1. add the init.lua file to the path ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\src\sengled.
2. Modified ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\fingerprints.yml file, a new device type E1L-G7K is added.


Please review and contact us promptly if you have any questions.










At 2023-04-20 00:09:39, "lelandblue" ***@***.***> wrote:

Hello - @anzhuge the init.lua file in ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\src\sengled is currently uploaded as a submodule. Please update this PR so that the init.lua file is present without a new submodule.

Also, please update the PR name to properly describe this PR, thanks!

you can refer to this other sengled device PR for reference: #374

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-04-25 03:34 UTC, anzhuge commented
1. add the init.lua file to the path ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\src\sengled.
2. Modified ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-water-leak-sensor\fingerprints.yml file, a new device type E1L-G7K is added.

2023-04-25 03:36 UTC, anzhuge commented
Hello, @lelandblue,

2023-05-02 18:45 UTC, ctowns reviewed
Also, please squash your commits before merging

2023-05-02 18:45 UTC, ctowns commented on drivers/SmartThings/zigbee-water-leak-sensor/src/sengled/init.lua
> +  NAME = "Sengled Water Leak Sensor  Handler",
nit:
```suggestion
  NAME = "Sengled Water Leak Sensor Handler",
```

2023-05-02 18:45 UTC, ctowns commented on drivers/SmartThings/zigbee-water-leak-sensor/fingerprints.yml
> +    manufacturer: sengled.
I believe the manufacturer name should just be "sengled"
```suggestion
    manufacturer: sengled
```

2023-05-04 06:36 UTC, anzhuge commented
Add Sengled rgbw bulb device
Modified ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-switch\src\rgbw-bulb\init.lua file, a new device type E23-N13 is added.
Modified ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-switch\fingerprints.yml file, a new device type E23-N13 is added.

2023-05-04 06:58 UTC, anzhuge commented
Add Sengled dimming light bulb device:
1. Modified ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-switch\src\zigbee-dimming-light\init.lua file, a new device type E23-N11 is added.
2. Modified ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-switch\fingerprints.yml file, a new device type E23-N11 is added.

2023-05-10 20:42 UTC, lelandblue commented
@ctowns / @greens Can you please review this?

2023-05-10 21:34 UTC, greens requested changes
sub-drivers must be `require`d in the base driver in order to be loaded and receive commands

2023-05-10 21:35 UTC, greens commented
conflicts need to be addressed with a rebase of the fork or the branch to origin/main

2023-05-11 06:18 UTC, anzhuge commented
> conflicts need to be addressed with a rebase of the fork or the branch to origin/main

I updated a color light and a white light on PR 615#. Can this be allowed?
PR 615# is my previous PR update on water leak sensor device.

2023-05-11 07:29 UTC, closed without merging