[CHAD-8243] Added metadata info for some siren profiles
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #71
Opened 2022-05-11 11:29 UTC by dsobierajsk

@SmartThingsCommunity/srpol-pe-team

2022-05-11 11:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=71) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=71) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=71) it.</sub>

2022-05-13 21:38 UTC, greens reviewed
Since it's not encapsulated in the names can you leave a comment in the profiles that indicates what's different about these vids?

2022-05-17 14:18 UTC, KKlimczukS requested changes

2022-05-17 14:18 UTC, KKlimczukS commented on drivers/SmartThings/zwave-siren/profiles/aeon-siren.yml
> +  mnmn: SmartThingsEdge
Please use "SmartThings" instead of "SmartThingsEdge" - applies to all files in this PR

2022-05-18 10:55 UTC, KKlimczukS approved these changes

2022-05-18 12:24 UTC, merged