add sengled zigee-contact and zigbee-motion-sensor
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #716
Opened 2023-05-08 03:06 UTC by sengled-desi

zigee-contact:
add the init.lua file to the path ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-contact\src\sengled.
modified ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-contact\fingerprints.yml file, a new device type E2D-G73 is added.
zigbee-motion-sensor:
add the init.lua file to the path ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-motion-sensor\src\sengled.
modified ~\SmartThingsEdgeDrivers\drivers\SmartThings\zigbee-motion-sensor\fingerprints.yml file, a new device type E1M-G7H is added.

2023-05-08 03:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=716) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=716) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=716) it.</sub>

2023-05-10 17:36 UTC, greens reviewed
Can you respond to my comment on the original PR:

>If you use this method, the battery voltage attribute will be configured for you using the defaults. The only difference between your config and the defaults is the max reporting interval, which is 21600 in the defaults.

>Similarly, your IAS Zone configuration is not that far removed from the defaults (a lower max interval of 300) and a nil reportable_change.

>I think, if you wanted, all you'd have to have is the linear_voltage_init. You could use tests to confirm that the results of the configure lifecycle event are what you expect.

2023-05-10 17:44 UTC, greens requested changes
This code is never included in the base drivers and will never be loaded as written.

2023-06-20 15:35 UTC, lelandblue commented
Hello @sengled-desi 

Please see our comments above. We need you to take action before WWST Certification can proceed. 1. Please see the comments above from @greens and make the changes recommended. 2. Please sign the CLA, this needs to be signed before we can merge the code. 

Thank you - if you have questions please reach out to partners@smartthings.com

2023-06-21 17:35 UTC, greens commented on drivers/SmartThings/zigbee-contact/src/init.lua
> +	require("smartsense-multi"),
spacing

2023-06-21 17:35 UTC, greens commented on drivers/SmartThings/zigbee-motion-sensor/src/init.lua
> +	require("thirdreality"),
same

2023-06-21 17:36 UTC, greens requested changes
Write some tests please.

2023-06-25 01:43 UTC, sengled-desi commented
@greens @lelandblue  Sorry, I was careless when modifying the file, this time the modification should be okay!

2023-06-27 17:31 UTC, greens requested changes
Would still like to see some tests. They don't need to to be big, since you're mostly just changing how the device responds to `doConfigure`, but we want to make sure that that behavior is not changed.

2023-07-06 01:32 UTC, lelandblue commented
Hey @sengled-desi Just a reminder in order for this to proceed please provide unit test.

2023-09-01 08:27 UTC, sengled-desi commented
@lelandblue  We have submitted several other products for certification earlier, but they all passed, this product is consistent with other products, I don't really clear what problems it has, if I need to submit some test units, what tools do I need to use to test which case

2023-09-05 21:23 UTC, greens commented
@sengled-desi hopefully this helps: https://developer.smartthings.com/docs/devices/hub-connected/test-your-driver/

We also have tons of examples in the repo. In general, devices that are just fingerprint adds and do not change any code don't need new unit tests since they're not using any new code, but for devices where there _are_ code changes, we like to have tests of that logic so that we can avoid changing it with any future changes.

2023-09-06 05:31 UTC, sengled-desi commented
Hey @greens  @lelandblue Since we don't have a test environment here, can you please help us test it? Our other products (pull: #724) are the same as the one I submitted, and there is no problem with those ones, so I think there should be no problem with this submission.

2023-09-06 18:55 UTC, greens commented
@sengled-desi These two links should help:

https://developer.smartthings.com/docs/devices/hub-connected/set-up-dev-env
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/releases

2023-10-23 03:21 UTC, sengled-desi commented
@greens   It’s difficult for us to setup the Unit Test environment for E1M-G7H. so is there any other way we can move forward ?

2023-10-23 14:39 UTC, lelandblue commented
@sengled-desi  Let me help clarify, we do not believe you need to set up an additional test environment. 

Instead, we are asking for additional code to be written in the form of unit test. The examples that are linked above and that were provided by Andrew are in a .text file. We do require that **unit tests** are written to cover this code as your pull request stands today since you are adding a sub-driver in the init file. 

We can help make sure that you have the information to move forward. Please let me know if you have questions.

2023-10-25 08:18 UTC, sengled-desi commented
@greens @lelandblue    The .text file in this link you said, I didn’t find it in front. You can directly provide me with a similar example file.

2023-10-25 11:44 UTC, lelandblue commented
Hello @sengled-desi Thank you for your communication. 

Here are some test file examples that are in the Zigbee Motion Sensor Driver that you can use as an example: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/tree/main/drivers/SmartThings/zigbee-motion-sensor/src/test

Here is also some test file examples that are for the Zigbee Contact Sensor. 
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/tree/main/drivers/SmartThings/zigbee-contact/src/test

Each of the test files, coordinate with the init files of those devices. Please let me know if you have some questions still.

2023-10-27 02:12 UTC, sengled-desi commented
@lelandblue @greens    Hello, let me ask two questions: 
1. It is our battery power as the product that we previously certified to use the battery percentage attribute. Whether we do n’t need to add Sub-Driver. Just help us add product support. 
2. 3.If The Sub-Driver is a Mandatory Requirement, then is my test driver uploaded directly on this page or submitted through github

2023-10-27 17:47 UTC, greens commented
@sengled-desi our issues are with this:

```
/home/runner/work/SmartThingsEdgeDrivers/SmartThingsEdgeDrivers/drivers/SmartThings/zigbee-motion-sensor/src/sengled/init.lua | 86% | ❌
-- | -- | --
```
and this:
```
/home/runner/work/SmartThingsEdgeDrivers/SmartThingsEdgeDrivers/drivers/SmartThings/zigbee-contact/src/sengled/init.lua | 86% | ❌
-- | -- | --
```

2023-10-30 10:14 UTC, sengled-desi commented
@lelandblue @greens    Hello, the test file has been added.  If you still can't test it, can you provide me with a sample test file? I have a lot of content not very clearly

2023-10-30 18:30 UTC, greens commented on drivers/SmartThings/zigbee-contact/src/test/test_sengled_contact_sensor.lua
> +-- Copyright 2022 SmartThings
date

2023-10-30 18:30 UTC, greens commented on drivers/SmartThings/zigbee-motion-sensor/src/test/test_sengled_motion.lua
> +-- Copyright 2022 SmartThings
date

2023-10-30 18:31 UTC, greens commented
@sengled-desi looks good and now your coverage is at 100% so it's not shown in the digest. Thank you.

2023-10-30 18:52 UTC, lelandblue commented
Hello @sengled-desi please update the copywrite dates on the new .test files and then we can consider this review complete. 

The PR will not be merged until the device completes testing.

2023-11-01 02:03 UTC, sengled-desi commented
@lelandblue  Hello, The copyright date on the .test file has been updated.

2023-11-01 21:06 UTC, greens approved these changes

2023-12-22 13:33 UTC, merged