[CHAD-8639] Added metadata info to pest-control-battery profile
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #78
Opened 2022-05-16 13:29 UTC by dsobierajsk

2022-05-16 13:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=78) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=78) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=78) it.</sub>

2022-05-17 10:39 UTC, KKlimczukS requested changes

2022-05-17 10:39 UTC, KKlimczukS commented on drivers/SmartThings/zwave-mouse-trap/profiles/pest-control-battery.yml
> +  mnmn: SmartThingsEdge
please change it to SmartThings

2022-05-17 11:37 UTC, KKlimczukS approved these changes

2022-05-17 17:46 UTC, greens approved these changes
don't forget to squash. Also let me know if you can merge or not. Still some kinks to work out on this repo.

2022-05-18 10:45 UTC, merged