add thirdreality multi-function light
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #790
Opened 2023-06-25 07:23 UTC by weihuan1111

Change-Id: I188792e689ada8ee624eb3ba11492419852a2303

2023-06-26 05:41 UTC, weihuan1111 commented
@brianj94 Hi, we have submit the certification for our three devices, but now, we have not receive the e-mail from UL to do WWST certification, is there any problem with the certification we submitted?
![7e01fefbf4f6b392856f7445a1a7953](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/assets/99949392/07542f5a-11d3-4324-a208-c519b73c4df6)

2023-06-26 17:04 UTC, Brianj94 commented
Hi @weihuan1111 , 

Thank you for following up on these device certifications. Currently we are still working through our internal code review process for these submissions. Once those are completed we will create the necessary tickets on our side to bring in UL and have their team scope testing, quotes, and a timeline.  

At this time there are no additional steps needed from your team. 

Thank you,
Brian J

2023-06-26 21:38 UTC, ctowns reviewed
A couple small changes. Also, please add some unit tests so that this code has proper coverage

2023-06-26 21:38 UTC, ctowns commented on drivers/SmartThings/zigbee-switch/src/thirdreality/init.lua
> +local THIRDREALITY_MOTIOM_CLUSTER = 0xFC00
Fix spelling here and below
```suggestion
local THIRDREALITY_MOTION_CLUSTER = 0xFC00
```

2023-06-26 21:38 UTC, ctowns commented on drivers/SmartThings/zigbee-switch/src/thirdreality/init.lua
> +local function present_value_attr_handler(driver, device, value, zb_rx)
rename this function to something more accurate like `motion_sensor_attr_handler` or `occupancy_attr_handler`

2023-06-26 21:38 UTC, ctowns commented on drivers/SmartThings/zigbee-switch/src/thirdreality/init.lua
> +local ATTR_TR = 0x0002
rename this constant something more descriptive like `MOTION_SENSOR_VALUE`

2023-06-27 05:59 UTC, weihuan1111 commented
> A couple small changes. Also, please add some unit tests so that this code has proper coverage

@ctowns How to add unit tests? And how to test the unit tests?

2023-06-27 14:16 UTC, lelandblue commented
Hello @weihuan1111 . 

Yes, unit test coverage is necessary. Please see the other comments on the 2 other Third Reality requests for more details on this topic. 


Thank you

2023-06-29 06:01 UTC, weihuan1111 commented
@lelandblue Test units has been added.

2023-06-30 00:53 UTC, weihuan1111 commented
@greens Test units has been added.

2023-07-05 16:46 UTC, greens commented
@weihuan1111 your tests do not run for the same reason as in https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/772

2023-07-06 02:05 UTC, weihuan1111 commented
@greens Fixed, please review it, thank you.

2023-07-06 16:58 UTC, greens requested changes
Please run your own tests locally before committing them here. We have provided you guides on how to do this.

Your tests do not run. I will not be telling you why because you should be running them yourself.

2023-07-07 06:54 UTC, weihuan1111 commented
@greens @Brianj94

2023-07-10 20:37 UTC, greens commented
@weihuan1111 If you are running locally and things are working it's because you have a file locally that is not a part of your pull request. Your tests, using only the files in your PR, still do not run.

The profile `on-off-level-rgbw-motion-sensor` referenced in your tests does not exist.

2023-07-11 00:20 UTC, weihuan1111 commented
@greens Fixed.

2023-07-11 17:26 UTC, greens commented
Your tests still do not run. Can you explain to me the issues you're having setting up the tests to run locally? If you tell me the problems you're having, maybe I can help.

2023-07-12 00:52 UTC, weihuan1111 commented
@greens  I found the problem, i lose the .yml in get_profile_definition.

2023-07-12 03:30 UTC, weihuan1111 commented
@greens I still have question. why i run other test, like test_on_off_zigbee_bulb.lua , still show "\profiles\on-off-level-intensity.yml: No such file or directory"

![6b48bfa740adeb9e4ebff45297a7fe7](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/assets/99949392/a4200659-0d5b-4eb9-b093-bfbab913a3f6)

2023-07-12 17:18 UTC, greens commented
@weihuan1111 tests should be run from the `/src` directory of the driver

2023-07-12 17:20 UTC, greens commented on drivers/SmartThings/zigbee-switch/src/thirdreality/init.lua
> +local THIRDREALITY_MOTION_CLUSTER = 0xFC00
you don't need to bind to or configure reporting for this cluster?

2023-07-13 20:23 UTC, greens approved these changes

2023-07-14 00:34 UTC, weihuan1111 commented
@Brianj94 Thank you, i have add the Firmware version and Product Category for the device in this pull request.

2023-08-16 18:17 UTC, Brianj94 commented
Hi @weihuan1111, I hope you are doing well. I wanted to follow up on this device certification as well as the Vibration Sensor. I see that it has not moved into testing with UL and I wanted to see if you've received the quote from UL and if samples have been sent. Please let me know if you have any info on the current status of this device. 

If samples have been sent and quote have been completed please let me know, and I will follow up with the UL team. 

Thank you,
Brian J

2023-08-17 03:05 UTC, weihuan1111 commented
@Brianj94 The button and vibration sensor have been sent to UL, and UL have received the devices.
We have received  the quote of the night light from UL, we have not sent the sample.

2023-08-17 16:45 UTC, Brianj94 commented
@weihuan1111 Okay, thank you for the update. I will push from my side to have the sensor and button move along through testing. Hope you have a good weekend.

2023-09-12 13:59 UTC, Brianj94 commented
Hi @weihuan1111 , I hope you are well. Can you please provide a timeline for when the Night Light quote will be processed and samples provided to UL?

2023-09-15 01:49 UTC, lelandblue commented
The status of this request has changed. If you have questions please reach out to partners@smartthings.com

Thank you.

2023-09-15 01:49 UTC, closed without merging