[CHAD-8545] Ported additional fingerprints of the 'Orvibo Moisture Sensor' for 'Third Reality 3RWS18BZ'
SmartThingsCommunity/SmartThingsEdgeDrivers pull request #98
Opened 2022-05-30 14:20 UTC by dsobierajsk

Original DTH: https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/orvibo-Moisture-Sensor.src/orvibo-Moisture-Sensor.groovy

@SmartThingsCommunity/srpol-pe-team

2022-05-30 14:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=98) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=98) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SmartThingsCommunity/SmartThingsEdgeDrivers?pullRequest=98) it.</sub>

2022-05-31 09:28 UTC, KKlimczukS requested changes

2022-05-31 09:28 UTC, KKlimczukS commented on drivers/SmartThings/zigbee-water-leak-sensor/src/test/test_thirdreality_water_leak_sensor.lua
> +    test.socket.capability:__set_channel_ordering("relaxed")
This might not needed to set in all those tests.

2022-05-31 10:22 UTC, KKlimczukS approved these changes
lgtm

2022-05-31 18:00 UTC, greens approved these changes

2022-06-01 08:30 UTC, merged